# src/telegram/chart_generator.py
import io
from PIL import Image, ImageDraw, ImageFont
from typing import Dict, Any
from utils.logger import get_logger

logger = get_logger(__name__)

class ChartGenerator:
    """
    A utility class to generate custom, information-rich images and charts
    for Telegram messages. This provides a more professional and visually
    appealing way to present data compared to plain text.
    """
    def __init__(self):
        """
        Initializes the ChartGenerator, attempting to load professional fonts.
        Falls back to a default font if specific .ttf files are not found.
        """
        try:
            # For a production system, you would place font files (e.g., from Google Fonts)
            # in a 'fonts' directory and reference them here.
            self.title_font = ImageFont.truetype("fonts/DejaVuSans-Bold.ttf", 28)
            self.body_font = ImageFont.truetype("fonts/DejaVuSans-Bold.ttf", 18)
            self.label_font = ImageFont.truetype("fonts/DejaVuSans.ttf", 16)
        except IOError:
            logger.warning("Custom font files not found. Falling back to default font.")
            self.title_font = ImageFont.load_default()
            self.body_font = ImageFont.load_default()
            self.label_font = ImageFont.load_default()

    async def create_status_dashboard(self, data: Dict[str, Any]) -> io.BytesIO:
        """
        Creates a comprehensive status dashboard image from various data points.

        Args:
            data (Dict[str, Any]): A dictionary containing all the data to be displayed.

        Returns:
            io.BytesIO: A bytes buffer containing the generated PNG image.
        """
        # Create a blank image with a dark, professional background
        img = Image.new('RGB', (600, 400), color='#1E222D')
        d = ImageDraw.Draw(img)

        # Draw a header line
        d.line([(20, 60), (580, 60)], fill='#3A3F4C', width=1)

        # Title
        d.text((20, 20), "System & Market Dashboard", font=self.title_font, fill='#FFFFFF')

        # --- Column 1: System & On-Chain ---
        col1_x = 40
        d.text((col1_x, 80), "VPS Health", font=self.body_font, fill='#5DADE2') # Blue
        d.text((col1_x, 110), f"CPU Usage: {data.get('cpu_usage', 0):.1f}%", font=self.label_font, fill='#FFFFFF')
        d.text((col1_x, 135), f"RAM Usage: {data.get('ram_usage', 0):.0f} MB", font=self.label_font, fill='#FFFFFF')

        d.text((col1_x, 190), "On-Chain Vitals", font=self.body_font, fill='#58D68D') # Green
        d.text((col1_x, 220), f"ETH Gas Price: {data.get('gas_price', 0):.1f} Gwei", font=self.label_font, fill='#FFFFFF')
        d.text((col1_x, 245), f"Dominant Narrative: {data.get('dominant_narrative', 'N/A')}", font=self.label_font, fill='#FFFFFF')
        
        # --- Column 2: Market & Bot Signal ---
        col2_x = 320
        d.text((col2_x, 80), "Market Sentiment", font=self.body_font, fill='#F5B041') # Orange
        fng_data = data.get('fear_greed', {})
        fng_value = fng_data.get('value', 0)
        fng_text = fng_data.get('value_classification', 'N/A')
        fng_color = '#2ECC71' if fng_value > 55 else '#E74C3C' if fng_value < 45 else '#F1C40F'
        d.text((col2_x, 110), f"Fear & Greed Index: {fng_value} ({fng_text})", font=self.label_font, fill=fng_color)
        d.text((col2_x, 135), f"BTC Price: ${data.get('btc_price', 0):,.2f}", font=self.label_font, fill='#FFFFFF')

        d.text((col2_x, 190), "Bot Signal", font=self.body_font, fill='#EC7063') # Red
        signal_strength = data.get('composite_signal_strength', 0)
        signal_color = '#2ECC71' if signal_strength > 0.6 else '#E74C3C' if signal_strength < 0.4 else '#F1C40F'
        d.text((col2_x, 220), f"Composite Strength: {signal_strength:.2f}", font=self.label_font, fill=signal_color)
        
        # --- Footer ---
        d.line([(20, 360), (580, 360)], fill='#3A3F4C', width=1)
        d.text((20, 370), "Generated by Elite Trading Bot", font=self.label_font, fill='#566573')


        # Convert the final image to a bytes buffer to be sent via Telegram
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)  # Rewind the buffer to the beginning
        return buffer
